# Generated by Django 3.2.8 on 2021-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('AVERAGE', 'average'), ('HIGH', 'high')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'bug'), ('IMPROVEMENT', 'improvement'), ('TASK', 'task')], max_length=100),
        ),
    ]
