# Generated by Django 3.2.8 on 2021-10-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='pernission',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='piority',
        ),
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('CONTRIB', 'contrib')], default='p1', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('AVERAGE', 'average'), ('HIGH', 'high')], default='pr1', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], default='s1', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'bug'), ('IMPROVEMENT', 'improvement'), ('TASK', 'task')], default='ta1', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('TYPE_1', 'type_1'), ('TYPE_2', 'type_2'), ('TYPE_3', 'type_3')], default='t1', max_length=100),
        ),
    ]
