# Generated by Django 3.2.8 on 2021-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_author_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
