# Generated by Django 3.2.8 on 2021-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0003_contributor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('AUTHOR', 'author'), ('CONTRIBUTOR', 'contributor')], max_length=11),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(max_length=128),
        ),
    ]
