# Generated by Django 3.2.8 on 2021-11-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0015_alter_contributor_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
